# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d39096cfe94cf3d96e88217319791d59cfe9699b1e2e8cd0ab9ec0c6b01f293a9964afa84ef5adac71a3755fd093fba294d21c18ebd2a740df64aa829c91efa

test:
  secret_key_base: 5ca45343571435ce7d2b9304001809cb12ed9a39c0a5bc57ed77ccf070c68812edbe8a9ea51022044bd7c532e26fd6d3bdabc1e1a424fb427a11d593273aab3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
